version: '3.4'
services:
  schedule-test:
    container_name: schedule-test
    build:
      dockerfile: Dockerfile.test
      context: .
      target: tests
    volumes:
      - .:/usr/src/schedule
      - ./usr/src/schedule/node_modules
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@schedule-postgres-test:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - schedule-postgres-test
    command: bash -c "npx prisma migrate dev && npm run test"
  schedule-postgres-test:
    container_name: schedule-postgres-test
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@schedule-postgres-test:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - schedule-postgres-test-data:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}

volumes:
  schedule-postgres-test-data:
