version: '3'
services:
  schedule-postgres:
    image: postgres
    container_name: schedule-postgres
    restart: always
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - schedule-postgres-data:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}
  schedule:
    build: 
      context: .
    container_name: schedule
    depends_on:
      - schedule-postgres
    working_dir: /usr/src/schedule
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/schedule/src
      - ./.env:/usr/src/heavy-news/.env
    ports:
      - ${PORT}:${PORT}
    command: bash -c "npx prisma generate && npx prisma migrate dev && npm run dev"
volumes:
  schedule-postgres-data: